# Generated by Django 3.2.19 on 2023-06-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230616_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid_for_google_form',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='googleform送信用のuuid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
