# Generated by Django 3.2.19 on 2023-06-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230616_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid_for_google_form',
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='uuid'),
        ),
    ]
