# Generated by Django 3.2.19 on 2023-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230618_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True, verbose_name='uuid'),
        ),
    ]
