# Generated by Django 3.2.19 on 2023-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(editable=False, max_length=40, unique=True, verbose_name='uuid'),
        ),
    ]
