# Generated by Django 3.2.19 on 2023-06-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AddField(
            model_name='user',
            name='uuid_for_google_form',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='googleフォームに送信するためのuuid'),
        ),
    ]
