# Generated by Django 3.2.20 on 2023-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_alter_deck_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='public_flag',
            field=models.BooleanField(default=False, verbose_name='全体公開'),
        ),
    ]
