# Generated by Django 3.2.19 on 2023-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioncard', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questioncard',
            constraint=models.UniqueConstraint(fields=('in_deck', 'order'), name='unique__in_deck__order'),
        ),
    ]
